// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "TestLib",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .library(
            name: "CppTest",
            targets: ["CppTest"]
        )
    ],
    targets: [
        .target(
            name: "CppTest",
            path: "./Sources/CppTest"
        )
    ],
    cxxLanguageStandard: CXXLanguageStandard(rawValue: "c++14")
)
